import { useState } from 'react';
import { Plus, Minus } from 'lucide-react';
import { useLanguage } from '../contexts/LanguageContext';

export default function FAQ() {
  const { t, language } = useLanguage();
  const [openIndex, setOpenIndex] = useState<number | null>(0);

  const faqs = [
    { question: 'How much can I save on my electricity bills?', answer: 'Most customers save 70-90% on their monthly electricity bills. The exact amount depends on your current consumption, solar system size, and sunlight availability in your area.' },
    { question: 'What is net-metering and how does it work?', answer: 'Net-metering allows you to sell excess electricity generated by your solar panels back to the grid. You receive credits that offset your electricity consumption during non-sunny hours, reducing your bills further.' },
    { question: 'How long do solar panels last?', answer: 'Solar panels typically last 25-30 years with minimal maintenance. We provide a 25-year performance warranty ensuring at least 80% efficiency after 25 years. Inverters may need replacement after 10-15 years.' },
    { question: 'What is the subsidy available for residential solar?', answer: 'The government provides 40% subsidy (₹18,000/kW) for systems up to 3kW and 20% subsidy (₹9,000/kW) for additional capacity from 3-10kW. Maximum subsidy is ₹78,000 for a 10kW system.' },
    { question: 'How long does installation take?', answer: 'Residential installations typically take 2-3 days for physical installation. The complete process including approvals and net-metering setup takes 2-4 weeks depending on local authority response times.' },
    { question: 'What maintenance is required?', answer: 'Solar panels require minimal maintenance. We recommend cleaning panels 2-3 times a year to remove dust. Our AMC plans include regular inspections, cleaning, performance monitoring, and priority support.' },
    { question: 'Are EMI options available?', answer: 'Yes! We partner with leading banks and NBFCs to offer flexible EMI options starting from 0% down payment. Loan tenures range from 1-7 years with competitive interest rates.' },
    { question: 'Will solar work during power cuts?', answer: 'Standard grid-tied systems do not work during power cuts for safety reasons. However, our hybrid systems with battery backup provide uninterrupted power supply even during grid outages.' },
  ];

  return (
    <section className="py-20 bg-gradient-to-br from-gray-50 to-white">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-16">
          <h2 className="text-4xl font-bold text-gray-900 mb-4">{t('faq')}</h2>
          <p className="text-xl text-gray-600">Get answers to common questions about solar energy</p>
        </div>

        <div className="space-y-4">
          {faqs.map((faq, index) => (
            <div key={index} className="bg-white rounded-2xl shadow-md hover:shadow-lg transition-all duration-300 overflow-hidden">
              <button onClick={() => setOpenIndex(openIndex === index ? null : index)} className="w-full px-8 py-6 flex items-center justify-between text-left hover:bg-gray-50 transition-colors">
                <span className="text-lg font-semibold text-gray-900 pr-8">{faq.question}</span>
                <div className="flex-shrink-0">
                  {openIndex === index ? (
                    <Minus className="h-6 w-6 text-blue-600" />
                  ) : (
                    <Plus className="h-6 w-6 text-blue-600" />
                  )}
                </div>
              </button>

              {openIndex === index && (
                <div className="px-8 pb-6 animate-fadeIn">
                  <p className="text-gray-600 leading-relaxed">{faq.answer}</p>
                </div>
              )}
            </div>
          ))}
        </div>

        <div className="mt-12 text-center bg-blue-50 rounded-2xl p-8">
          <h3 className="text-2xl font-bold text-gray-900 mb-3">Still have questions?</h3>
          <p className="text-gray-600 mb-6">Our team is here to help you make the right decision</p>
          <a href="#contact" className="inline-flex items-center bg-gradient-to-r from-blue-600 to-blue-700 text-white px-8 py-3 rounded-lg hover:from-blue-700 hover:to-blue-800 transition-all font-medium shadow-lg">
            {t('contactUs')}
          </a>
        </div>
      </div>
    </section>
  );
}
